### ISSUE TITLE
There is an error on dashboard as soon as you register and access the system very first time

### ISSUE THREAD

**Issue by thecodeholic** [thecodeholic/laravel8-vue3-survey#3]

**Comment by Azam2926** [comment]
### Hello Zura nice to chat with you again, what kind of error that you meant ?



![Screenshot from 2022-01-19 19-25-39](https://user-images.githubusercontent.com/28877486/150150185-39021165-dd3d-4c9d-82a8-532b8def72ef.png)

#### i've not seen any errors on dashboard
i've installed app on my local machine, registered and not seen any errors

**Comment by thecodeholic** [comment]
@Azam2926 Actually it is already fixed. So I will close this issue.
