### ISSUE TITLE
error loading the index.css file

### ISSUE THREAD

**Issue by ghost** [thecodeholic/laravel8-vue3-survey#5]
I follow all each step to install vite, vue and tailwindcss; but when I run with the login template from tailwindcssui, I got this error:

In main.js I import the tailwinds.css
![imagen](https://user-images.githubusercontent.com/94011774/150689163-9e3b6465-3ae9-4ecd-bb30-2ecb21106b22.png)

the tailwinds.css file has:
![imagen](https://user-images.githubusercontent.com/94011774/150689285-146debfe-64f8-4af0-a7ae-2a70ba897c24.png)

I wrote on tailwinds.config.js
![imagen](https://user-images.githubusercontent.com/94011774/150689228-8cb9e126-c13d-4e43-8176-07cc89ea2389.png)

in HelloWorld.vue component has:
![imagen](https://user-images.githubusercontent.com/94011774/150689337-10e16cb7-6a44-433e-be3a-4481ec5264e2.png)

And me error showed is:
![imagen](https://user-images.githubusercontent.com/94011774/150689655-520e3586-12e3-4fc2-b2cf-b6188c8652e4.png)

What am I doing wrong?

**Comment by thecodeholic** [comment]
@hombre-geek Is your config file called `tailwinds.config.js`? It should be `tailwind.config.js` without `s`.

**Comment by ghost** [comment]
> @hombre-geek Is your config file called `tailwinds.config.js`? It should be `tailwind.config.js` without `s`.

It was a mistake here when I wrote the issue, but you can see the image that the filename is well written.

**Comment by thecodeholic** [comment]
@hombre-geek The error comes from App.vue can you provide the screenshot for App.vue?

**Comment by ghost** [comment]
> @hombre-geek The error comes from App.vue can you provide the screenshot for App.vue?

Here is:
![imagen](https://user-images.githubusercontent.com/94011774/150699576-5771c969-470f-4e1a-b7f9-dda9341eeef5.png)

**Comment by ghost** [comment]
I tell you that I was able to solve the issue.
The problem was that I had installed tailwindcss in the root of the Laravel project, and not the directory where Vue is located.

I managed to solve it, so pay attention to the video when looking at where to install this part, since it is not mentioned that it should be done in the root of Vue.

**Comment by thecodeholic** [comment]
Right here I mention that you need to run commands from `vue` folder. But I agree would be more clear if I highlight that certain commands must be run from `vue` folder and don't mistakenly run them from laravel project folder.
https://youtu.be/WLQDpY7lOLg?t=1295
