### ISSUE TITLE
cannot npm run dev

### ISSUE THREAD

**Issue by DelvinWillian** [thecodeholic/laravel8-vue3-survey#7]
Pre-bundling dependencies:
  vue
(this will be run only when your dependencies or config have changed)
X [ERROR] Failed to write to output file: open C:\...\laravel-vue-survey\vue\node_modules\.vite\vue.js.map: The system cannot find the file specified.

X [ERROR] Failed to write to output file: open C:\...\laravel-vue-survey\vue\node_modules\.vite\vue.js: The system cannot find the file specified.

$ npm -v
8.3.1

$ node -v
v16.14.0

There is error when npm run dev, been searching for solution. but still got the same error..

**Comment by thecodeholic** [comment]
Did you try to remove node_modules folder and re-run `npm install && npm run dev`

**Comment by DelvinWillian** [comment]
my bad, i forgot to enter "cd vue"
