### ISSUE TITLE
"state.dashboard.data" is empty

### ISSUE THREAD

**Issue by mikseros** [thecodeholic/laravel8-vue3-survey#8]
During implementing Dashboard, the dashboard.data is empty
<a href="https://ibb.co/YRvqxDx"><img src="https://i.ibb.co/YRvqxDx/dashboard.jpg" alt="dashboard" border="0"></a>
But surveys, questions & answers exists in the database.

**Comment by thecodeholic** [comment]
Please have a look in console. There might be an error.

**Comment by mikseros** [comment]
> Please have a look in console. There might be an error.

<a href="https://ibb.co/PCFnq15"><img src="https://i.ibb.co/PCFnq15/dash2.jpg" alt="dash2" border="0"></a>

Ok, I will try to resolve that now. Thank you, probably (surely) it is my fault.

**Comment by thecodeholic** [comment]
I think the server returns with 500 status code.
The problem should be in API.

**Comment by mikseros** [comment]
> I think the server returns with 500 status code. The problem should be in API.

Probably, the problem is here:
<a href="https://ibb.co/fShvRvr"><img src="https://i.ibb.co/fShvRvr/dash3.jpg" alt="dash3" border="0"></a>
<a href="https://ibb.co/qY1R6Kq"><img src="https://i.ibb.co/qY1R6Kq/dash4.jpg" alt="dash4" border="0"></a>

But when I am changing image_url to image, I have this error:
<a href="https://ibb.co/nRLpF27"><img src="https://i.ibb.co/nRLpF27/dash5.jpg" alt="dash5" border="0"></a>
<a href="https://ibb.co/LR1Gg9T"><img src="https://i.ibb.co/LR1Gg9T/dash6.jpg" alt="dash6" border="0"></a>

**Comment by thecodeholic** [comment]
Try to debug and see what data is inside `data.latestSurvey`.

**Comment by mikseros** [comment]
> Try to debug and see what data is inside `data.latestSurvey`.

Ok, Boss.
I found it. FInally. It works. 
<a href="https://ibb.co/9YvWS8T"><img src="https://i.ibb.co/9YvWS8T/dash7.jpg" alt="dash7" border="0"></a>
Thank you for your assistance. I really appreciate it!
The problem was located in DashoboardController
Have a great day!

**Comment by thecodeholic** [comment]
Great to know that its working. I will close the issue than.
Good luck
